### ISSUE TITLE
Add new text for calibration

### ISSUE THREAD

**Issue by Louiseva92** [NIVANorge/ds_extended_metadata#3]
Draft for calibration text. Can you check @andrewkingniva ?

Chlorophyll-a fluorescence:

The chl-a fluorescence is calibrated using algae from culture. NIVA use the diatom Skeletonema pseudocostatum sampled from Oslofjorden. The calibration is performed in dark conditions by using filtrated seawater as a blank followed by adding known concentration of the algae culture. Filtrated chlorophyll-a samples are taken for each added concentration of algae culture and analyzed spectrophotometrically (refereanse?).  The raw counts from the sensor are compared with the chlorophyll-a concentration and a linear trendline gives the calibration equation.

cDOM fluorescence (fdom)
fDOM is calibrated using freshly prepared quinine sulphate (QS) standards from a stock solution of 7040 mg/m3 in 0.05 M sulfuric acid in the concentration range 0-200 mg/m3. Calibration is done in dark conditions. Blank is measured with both milliQ water and 0.05 M sulfuric acid, followed by adding known concentrations of QS. The different concentrations of QS are compared to the raw counts from the sensor by a linear trendline that gives the calibration equation. 

Turbidity
Turbidity is calibrated using formazi in dark conditions. MilliQ water is used as a blank, followed by adding formazin from low to high concentration. Each new concentration of formazin, the sample is also measured with a reference turbidimeter (Hatch). The results from the turbidimeter are compared with the raw counts from the sensor with a linear trendline that gives a calibration equation. 

To adjust the master calibration to different C3 instruments we use solid standards to create a factor difference between two instruments. Each C3 instrument has its own set of solid standards containing one low reading and one high reading for fDOM, chl-a fluorescence and turbidity. The solid standards are measured on its belonging C3 instrument and the master calibrated sensor. A factor for each of the three parameters is created by the difference between the two sensors, and this factor is added to the calibration equations. After adding the factor to the master calibration on a sensor, it is called “sensor adjusted”

**Comment by andrewkingniva** [comment]
Slightly modified the text. I think we should not include the solid standards paragraph.
-for chl-a, should we say e.g. Skeletonema? Or maybe not even mention the species?
-for chl-a, can we add a range of chl-a 0-X ug/L?
-for turbidity, can we add units (FNU?) a range of 0-X FNU? 

Chlorophyll-a fluorescence (chl-a):
Chl-a fluorescence is calibrated using phytoplankton from culture. NIVA uses the diatom _Skeletonema pseudocostatum_ collected from Oslofjorden. The calibration is performed in dark conditions using filtered seawater as a blank followed by adding a known concentration of the phytoplankton culture. Filtered chl-a samples are taken for each added concentration of algae culture and analyzed spectrophotometrically (reference). The raw counts from the sensor are used with the chl-a concentration to generate a linear calibration equation.

cDOM fluorescence (fDOM):
fDOM is calibrated using freshly prepared quinine sulphate (QS) standards from a stock solution of 7040 mg/m3 in 0.05 M sulfuric acid in the concentration range 0-200 mg/m3 QS. Calibration is done in dark conditions. Blank is measured with both ultrapure water (Milli-Q) and 0.05 M sulfuric acid, followed by adding known concentrations of QS. The different concentrations of QS are compared to the raw counts from the sensor to generate a linear calibration equation.

Turbidity:
Turbidity is calibrated using formazin in dark conditions. Milli-Q water is used as a blank, followed by adding formazin from low to high concentration. For each concentration of formazin, the sample is also measured with a reference turbidimeter (Hach). The results from the turbidimeter are compared with the raw counts from the sensor to generate a linear calibration equation.

**Comment by andrewkingniva** [comment]
@Louiseva92

**Comment by Louiseva92** [comment]
@andrewkingniva , new text with units. and changed sentence about algae. 


Chlorophyll-a fluorescence (chl-a):
Chl-a fluorescence is calibrated using phytoplankton from culture within a range of 0 - 20 µg/L. NIVA uses a common algae from the monitoring area, e.g. _Skeletonema_ spp. The calibration is performed in dark conditions using filtered seawater as a blank followed by adding a known concentration of the phytoplankton culture. Filtered chl-a samples are taken for each added concentration of algae culture and analyzed spectrophotometrically (reference). The raw counts from the sensor are used with the chl-a concentration to generate a linear calibration equation.

cDOM fluorescence (fDOM):
fDOM is calibrated using freshly prepared quinine sulphate (QS) standards from a stock solution of 7040 mg/m3 in 0.05 M sulfuric acid in the concentration range 0-200 mg/m3 QS. Calibration is done in dark conditions. Blank is measured with both ultrapure water (Milli-Q) and 0.05 M sulfuric acid, followed by adding known concentrations of QS. The different concentrations of QS are compared to the raw counts from the sensor to generate a linear calibration equation.

Turbidity:
Turbidity is calibrated using formazin in dark conditions within a range of 0 - 40 FNU. Milli-Q water is used as a blank, followed by adding formazin from low to high concentration. For each concentration of formazin, the sample is also measured with a reference turbidimeter (Hach). The results from the turbidimeter are compared with the raw counts from the sensor to generate a linear calibration equation.

**Comment by andrewkingniva** [comment]
@lisapro The most recent version is ok to use. 👍🏽
